INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Sulma Yaneth, El Salvador, 2608011);
INSERT INTO borrowers (name, location, image) VALUES (Gladys, Kenya, 2606638);
INSERT INTO borrowers (name, location, image) VALUES (Dorothy, Bafut Province, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Joanina, , 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
INSERT INTO borrowers (name, location, image) VALUES (Litia, Samoa, 2606639);
